[package]
name = "rust-esp32c3-example"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-idf-sys = { version = "0.22.2", features = ["std", "native", "binstart"] }

[build-dependencies]
embuild = "0.25.0"
